USE [GTStage_Matt]
GO
/****** Object:  StoredProcedure [dbo].[HGBR_DROPS]    Script Date: 9/25/2020 1:58:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER   procedure [dbo].[HGBR_DROPS] AS

IF OBJECT_ID('HGBR_GT', 'U') IS NOT NULL
	DROP TABLE HGBR_GT;

IF OBJECT_ID('HGBR_BRASPAG', 'U') IS NOT NULL
	DROP TABLE HGBR_BRASPAG;

-- HGBR PAYPAL SALES TABLES

IF OBJECT_ID('HGBR_BRASPAG', 'U') IS NOT NULL
	DROP TABLE HGBR_BRASPAG;

IF OBJECT_ID('HGBR_PP_JE', 'U') IS NOT NULL
	DROP TABLE HGBR_PP_JE;
	
IF OBJECT_ID('HGBR_Paypal_GT_Summ', 'U') IS NOT NULL
	DROP TABLE HGBR_Paypal_GT_Summ;

IF OBJECT_ID('HGBR_Paypal_GT_Tax_Summ', 'U') IS NOT NULL
	DROP TABLE HGBR_Paypal_GT_Tax_Summ;

IF OBJECT_ID('HGBR_Paypal', 'U') IS NOT NULL
	DROP TABLE HGBR_Paypal;

IF OBJECT_ID('HGBR_GT_PP_Suspense', 'U') IS NOT NULL
	DROP TABLE HGBR_GT_PP_Suspense;

IF OBJECT_ID('HGBR_PP_Suspense', 'U') IS NOT NULL
	DROP TABLE HGBR_PP_Suspense;

IF OBJECT_ID('HGBR_GT_PP_FullOuterJoin', 'U') IS NOT NULL
	DROP TABLE HGBR_GT_PP_FullOuterJoin;

IF OBJECT_ID('HGBR_PP_Suspense_JE', 'U') IS NOT NULL
	DROP TABLE HGBR_PP_Suspense_JE;

IF OBJECT_ID('HGBR_PP_Cbacks_JE', 'U') IS NOT NULL
	DROP TABLE HGBR_PP_Cbacks_JE;

IF OBJECT_ID('HGBR_PP_Fees_JE', 'U') IS NOT NULL
	DROP TABLE HGBR_PP_Fees_JE;

IF OBJECT_ID('HGBR_PP_Cash_JE', 'U') IS NOT NULL
	DROP TABLE HGBR_PP_Cash_JE;

IF OBJECT_ID('HGBR_PP_Total_Cash', 'U') IS NOT NULL
	DROP TABLE HGBR_PP_Total_Cash;

IF OBJECT_ID('HGBR_PP_JE_Final', 'U') IS NOT NULL
	DROP TABLE HGBR_PP_JE_Final;

IF OBJECT_ID('HGBR_Paypal_Exception_Report', 'U') IS NOT NULL
	DROP TABLE HGBR_Paypal_Exception_Report;
