USE [GTStage_Matt]
GO
/****** Object:  StoredProcedure [dbo].[HGMX_DROPS]    Script Date: 11/1/2020 1:18:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER   PROCEDURE [dbo].[HGMX_DROPS] AS

IF OBJECT_ID('HGMX_GT', 'U') IS NOT NULL
	DROP TABLE HGMX_GT;

IF OBJECT_ID('HGMX_GT_DLOCAL', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_DLOCAL;

IF OBJECT_ID('HGMX_DLOCAL', 'U') IS NOT NULL
	DROP TABLE HGMX_DLOCAL;

IF OBJECT_ID('HGMX_GT_Summ_Rev', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_Summ_Rev;

IF OBJECT_ID('HGMX_DLOCAL_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_DLOCAL_JE;

IF OBJECT_ID('HGMX_GT_Summ_Tax', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_Summ_Tax;

IF OBJECT_ID('HGMX_DLOCAL_FEES', 'U') IS NOT NULL
	DROP TABLE HGMX_DLOCAL_FEES;

IF OBJECT_ID('HGMX_GT_DLOCAL_FULLJOIN', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_DLOCAL_FULLJOIN;

IF OBJECT_ID('HGMX_GT_DLOCAL_FULLOUTERJOIN', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_DLOCAL_FULLOUTERJOIN;
	
IF OBJECT_ID('HGMX_DLOCAL_EXCEPTION_REPORT', 'U') IS NOT NULL
	DROP TABLE HGMX_DLOCAL_EXCEPTION_REPORT;

IF OBJECT_ID('HGMX_DLOCAL_Summ_Exceptions', 'U') IS NOT NULL
	DROP TABLE HGMX_DLOCAL_Summ_Exceptions;

IF OBJECT_ID('HGMX_DLOCAL_CBACKS', 'U') IS NOT NULL
	DROP TABLE HGMX_DLOCAL_CBACKS;

IF OBJECT_ID('HGMX_DLOCAL_CBacks_Summ', 'U') IS NOT NULL
	DROP TABLE HGMX_DLOCAL_CBacks_Summ;

IF OBJECT_ID('DLOCAL_AR_Summ_Temp', 'U') IS NOT NULL
	DROP TABLE DLOCAL_AR_Summ_Temp;

IF OBJECT_ID('DLOCAL_AR_Summ_Cbacks', 'U') IS NOT NULL
	DROP TABLE DLOCAL_AR_Summ_Cbacks;

IF OBJECT_ID('DLOCAL_AR_Summ', 'U') IS NOT NULL
	DROP TABLE DLOCAL_AR_Summ;
	
IF OBJECT_ID('HGMX_AR_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_AR_JE;

IF OBJECT_ID('HGMX_AR_TOTAL', 'U') IS NOT NULL
	DROP TABLE HGMX_AR_TOTAL;

IF OBJECT_ID('HGMX_DLOCAL_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_DLOCAL_JE;

IF OBJECT_ID('HGMX_DLOCAL_SALES_JE_FINAL', 'U') IS NOT NULL
	DROP TABLE HGMX_DLOCAL_SALES_JE_FINAL;

IF OBJECT_ID('HGMX_DLOCAL_FX_ADJ', 'U') IS NOT NULL
	DROP TABLE HGMX_DLOCAL_FX_ADJ;

-- HGMX_PAYPAL_SALES SPS

IF OBJECT_ID('HGMX_Paypal_GT_Summ', 'U') IS NOT NULL
	DROP TABLE HGMX_Paypal_GT_Summ;

IF OBJECT_ID('HGMX_PP_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_PP_JE;

IF OBJECT_ID('HGMX_Paypal', 'U') IS NOT NULL
	DROP TABLE HGMX_Paypal;

IF OBJECT_ID('HGMX_Paypal_GT_Tax_Summ', 'U') IS NOT NULL
	DROP TABLE HGMX_Paypal_GT_Tax_Summ;

IF OBJECT_ID('HGMX_GT_PP_Suspense', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_PP_Suspense;

IF OBJECT_ID('HGMX_PP_Suspense', 'U') IS NOT NULL
	DROP TABLE HGMX_PP_Suspense;

IF OBJECT_ID('HGMX_GT_Paypal_FullJoin', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_Paypal_FullJoin;

IF OBJECT_ID('HGMX_GT_PP_FullOuterJoin', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_PP_FullOuterJoin;

IF OBJECT_ID('HGMX_PP_Suspense_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_PP_Suspense_JE;

IF OBJECT_ID('HGMX_PP_Cbacks_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_PP_Cbacks_JE;

IF OBJECT_ID('HGMX_PP_Fees_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_PP_Fees_JE;

IF OBJECT_ID('HGMX_PP_Cash_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_PP_Cash_JE;

IF OBJECT_ID('HGMX_PP_Total_Cash', 'U') IS NOT NULL
	DROP TABLE HGMX_PP_Total_Cash;

IF OBJECT_ID('HGMX_PP_JE_Final', 'U') IS NOT NULL
	DROP TABLE HGMX_PP_JE_Final;

IF OBJECT_ID('HGMX_Paypal_Exception_Report', 'U') IS NOT NULL
	DROP TABLE HGMX_Paypal_Exception_Report;

-- PayU Sales Tables

IF OBJECT_ID('HGMX_PAYU_GT_Summ', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU_GT_Summ;

IF OBJECT_ID('HGMX_PAYU_GT_Tax_Summ', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU_GT_Tax_Summ;

IF OBJECT_ID('HGMX_PAYU_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU_JE;

IF OBJECT_ID('HGMX_PAYU', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU;

IF OBJECT_ID('HGMX_GT_PAYU_Suspense', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_PAYU_Suspense;

IF OBJECT_ID('HGMX_GT_PAYU_FullJoin', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_PAYU_FullJoin;

IF OBJECT_ID('HGMX_GT_PAYU_FullOuterJoin', 'U') IS NOT NULL
	DROP TABLE HGMX_GT_PAYU_FullOuterJoin;

IF OBJECT_ID('HGMX_PAYU_Suspense', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU_Suspense;

IF OBJECT_ID('HGMX_PAYU_Suspense_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU_Suspense_JE;

IF OBJECT_ID('HGMX_PAYU_Cbacks_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU_Cbacks_JE;

--		HGMX_PAYU_Fees_JE

IF OBJECT_ID('HGMX_PAYU_Cash_JE', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU_Cash_JE;

IF OBJECT_ID('HGMX_PAYU_Total_Cash', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU_Total_Cash;

IF OBJECT_ID('HGMX_PAYU_JE_Final', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU_JE_Final;

IF OBJECT_ID('HGMX_PAYU_Exception_Report', 'U') IS NOT NULL
	DROP TABLE HGMX_PAYU_Exception_Report;
	
	
