USE [GTStage_Matt]
GO


-- HGMX Paypal Sales SPS

ALTER PROCEDURE HGMX_PAYPAL_SALES @vDate VARCHAR(25) AS

--EXEC HGMX_DROPS

--DECLARE @vDate VARCHAR(50)
--SET @vDate = '20200602'

DECLARE @vDate_Datetime DATETIME
SET @vDate_Datetime = @vDate

DECLARE @vDate_MMddyyyy VARCHAR(20)
SET @vDate_MMddyyyy = FORMAT(@vDate_Datetime, 'MMddyyyy')

-- Summarize revenue from Paypal txns in GT Report

SELECT
	COMPANY_CALC
	, TYPE_CALC
	, BUSINESS_LINE_CALC
	, Currency
	, SUM(REVENUE_AMOUNT_USD_CALC) AS REVENUE_AMOUNT_USD_CALC
	, @vDate_MMddyyyy AS zPaypal_Date
INTO
	HGMX_Paypal_GT_Summ
FROM
	HGMX_GT
WHERE
	Settledby_Calc = 'Paypal'
GROUP BY
	COMPANY_CALC
	, TYPE_CALC
	, BUSINESS_LINE_CALC
	, Currency

EXEC spAddFieldstoJE @AlterTableName = 'HGMX_Paypal_GT_Summ'
EXEC spUpdateJE @TabletoUpdate = 'HGMX_Paypal_GT_Summ'
	, @CHECKBOOKID = 'PAYPAL'
	, @BATCHID = @vDate_MMddyyyy
	, @TRANTYPE = 5
	, @TRANDATE = @vDate_MMddyyyy

UPDATE A SET A.ACCOUNT = ISNULL(B.Account_Num, 'XXX-XXXXX-XXX')
FROM HGMX_Paypal_GT_Summ A
LEFT JOIN GTStage_Matt.dbo.hgmx_accounts_matrix B	ON A.TYPE_CALC = B.TYPE_CALC AND A.BUSINESS_LINE_CALC = B.BUSINESS_LINE_CALC;

UPDATE HGMX_Paypal_GT_Summ SET REFERENCE = zPaypal_Date + ' CASH PAYPAL'
UPDATE HGMX_Paypal_GT_Summ SET DEBIT = (CASE WHEN REVENUE_AMOUNT_USD_CALC > 0 THEN 0 ELSE REVENUE_AMOUNT_USD_CALC * -1 END)
UPDATE HGMX_Paypal_GT_Summ SET CREDIT = (CASE WHEN REVENUE_AMOUNT_USD_CALC < 0 THEN 0 ELSE REVENUE_AMOUNT_USD_CALC END )
UPDATE HGMX_Paypal_GT_Summ SET DISTREF = COMPANY_CALC + ' ' + TYPE_CALC + ' ' + BUSINESS_LINE_CALC + ' ' + Currency + ' - PAYPAL SALES'
UPDATE HGMX_Paypal_GT_Summ SET UNIQUEID = 'HGMXPP' + @vDate_MMddyyyy + @vDate_MMddyyyy

SELECT CHECKBOOKID, BATCHID, TRANTYPE, TRANDATE, SRCDOC, CURRID, REFERENCE, ACCOUNT, DEBIT, CREDIT, DISTREF, KEY1, REVERSEDATE, UNIQUEID INTO HGMX_PP_JE FROM HGMX_Paypal_GT_Summ
